[phases.setup]
nixPkgs = ["python313"]

[phases.install]
cmds = [
  "cd Phase-2-Web-App/backend",
  "pip install -r requirements.txt"
]

[phases.build]
cmds = ["cd Phase-2-Web-App/backend"]

[start]
cmd = "cd Phase-2-Web-App/backend && uvicorn app.main:app --host 0.0.0.0 --port $PORT"
